version: '3.3'
services:
  localstack:
    restart: always
    image: localstack/localstack:0.9.6
    ports:
      - "4567-4584:4567-4584"
      - "8080:8080"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-west-2
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack:/tmp/localstack
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
volumes:
  localstack:
    driver: local