AWSTemplateFormatVersion: '2010-09-09'
Description: Next Action App
Resources:
  TableNextAction:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: 'PAY_PER_REQUEST'
      TableName: "NextAction"